services:
  postgres:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME:-boilerplate}-postgres
    # Load environment variables from .env.project file
    env_file:
      - .env.project
    environment:
      POSTGRES_USER: ${DB_USER:-auth_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-auth_password}
      POSTGRES_DB: ${DB_NAME:-auth_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-auth_user} -d ${DB_NAME:-auth_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network



volumes:
  postgres_data:
    name: ${PROJECT_NAME:-boilerplate}-postgres-data

networks:
  app-network:
    name: ${PROJECT_NAME:-boilerplate}-network